version: "3"
services:
  golangserver:
    container_name: golangserver
    build: .
    ports:
      - "8080:8080"
    networks:
      - golangserver
    volumes:
      - .:/app

  #mariadb
  # mariadb:
  #   container_name: mariadb
  #   image: mariadb
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: golang
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - golangserver


networks:
  golangserver:
    driver: bridge
